default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: nitrous
  password:

development:
  <<: *default
  database: theme5_dev

test:
  <<: *default
  database: theme5_test

production:
  database: <%= ENV["DATABASE_URL"] %>